control "SV-216225" do
  title "The operating system must conduct backups of user-level information contained in the 
operating system per organization-defined frequency to conduct backups consistent with 
recovery time and recovery point objectives."
  desc "Operating system backup is a critical step in maintaining data assurance and availability. 


User-level information is data generated by information system and/or application 
users.

Backups shall be consistent with organizational recovery time and recovery point 
objectives."
  desc "check", "The operations staff shall ensure that proper backups are created, tested, and archived. 


Ask the operator for documentation on the backup procedures implemented.

If the backup 
procedures are not documented then this is a finding."
  desc "fix", "The operations staff shall install, configure, test, and verify operating system backup 
software.

Additionally, all backup procedures must be documented."
  impact 0.5
  tag severity: "medium"
  tag gtitle: "SRG-OS-000480"
  tag gid: "V-216225"
  tag rid: "SV-216225r603268_rule"
  tag stig_id: "SOL-11.1-090050"
  tag fix_id: "F-17461r373058_fix"
  tag legacy: ["SV-60849","V-47977"]
  tag cci: ["CCI-000366"]
  tag nist: ["CM-6 b"]
end